# Generated by Django 3.2.5 on 2021-07-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210721_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
