# Generated by Django 3.2.5 on 2021-07-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210708_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('zh-hans', 'Chinese')], max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('zh-hans', 'Chinese')], max_length=7),
        ),
    ]
